org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.1.44
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.06.26-1.20.1
license=LGPL-3.0

archive_base_name=nffservices-1.20.1
jei_version=15.2.0.27

mod_id=nffservices
group_id=net.sodiumzh.nff.services
authors=SodiumZH

nff_mod_id=nffservices
nff_name=NFF Services
nff_group_id=net.sodiumzh.nff.services
nff_license=LGPL-3.0
nff_authors=SodiumZH
nff_description=Natrium Friending Framework - A framework for taming and friendly mobs.

nff_version=0.2.32
filename_version=0.2.32-dev

nfu_version=0.2.32-dev
nfu_version_range=[0.2.32, 0.2.33)
