org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=40.2.4
forge_version_range=[40,)
loader_version_range=[40,)
mapping_channel=parchment
mapping_version=2022.08.07-1.18.2
mod_id=nffservices
archive_base_name=nffservices-1.18.2
mod_name=NFF Services
license=LGPL-3.0
mod_group_id=net.sodiumzh.nff.services
mod_authors=sodiumzh
mod_description=A toolkit for taming and friendly mobs.
jei_version=9.7.0.194
mixinextras_version=0.3.1
mixinextras_min_version=0.3.0

common_mod_id=nffservices
common_group_id=net.sodiumzh
common_authors=SodiumZH

nfu_mod_id=nautils
nfu_name=NFU Library
nfu_group_id=net.sodiumzh.nautils
nfu_license=LGPL-3.0
nfu_authors=SodiumZH
nfu_description=Natrium Forge Utilities - miscellaneous utilities for Forge game mechanics.

nff_mod_id=nffservices
nff_name=NFF Services
nff_group_id=net.sodiumzh.nff.services
nff_license=LGPL-3.0
nff_authors=SodiumZH
nff_description=Natrium Friending Framework - A framework for taming and friendly mobs.

filename_version=0.0.30-dev
nfu_version=0.0.30
nfu_version_range=[0.0.30, 0.0.31)
nff_version=0.0.30
