package net.sodiumstudio.nautils.block;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.sodiumstudio.nautils.math.WithStandardColors;

public class ColoredBlocks
{
	public static final WithStandardColors<Block> WOOL_BLOCKS = WithStandardColors.of(
			Blocks.WHITE_WOOL, Blocks.BLACK_WOOL, Blocks.GRAY_WOOL, Blocks.LIGHT_GRAY_WOOL,
			Blocks.RED_WOOL, Blocks.GREEN_WOOL, Blocks.BLUE_WOOL, Blocks.YELLOW_WOOL,
			Blocks.LIGHT_BLUE_WOOL, Blocks.MAGENTA_WOOL, Blocks.CYAN_WOOL, Blocks.ORANGE_WOOL, 
			Blocks.LIME_WOOL, Blocks.PURPLE_WOOL, Blocks.BROWN_WOOL, Blocks.PINK_WOOL);
	
	public static final WithStandardColors<Block> CARPET_BLOCKS = WithStandardColors.of(
			Blocks.WHITE_CARPET, Blocks.BLACK_CARPET, Blocks.GRAY_CARPET, Blocks.LIGHT_GRAY_CARPET,
			Blocks.RED_CARPET, Blocks.GREEN_CARPET, Blocks.BLUE_CARPET, Blocks.YELLOW_CARPET,
			Blocks.LIGHT_BLUE_CARPET, Blocks.MAGENTA_CARPET, Blocks.CYAN_CARPET, Blocks.ORANGE_CARPET, 
			Blocks.LIME_CARPET, Blocks.PURPLE_CARPET, Blocks.BROWN_CARPET, Blocks.PINK_CARPET);
	
	public static final WithStandardColors<Block> BANNER_BLOCKS = WithStandardColors.of(
			Blocks.WHITE_BANNER, Blocks.BLACK_BANNER, Blocks.GRAY_BANNER, Blocks.LIGHT_GRAY_BANNER,
			Blocks.RED_BANNER, Blocks.GREEN_BANNER, Blocks.BLUE_BANNER, Blocks.YELLOW_BANNER,
			Blocks.LIGHT_BLUE_BANNER, Blocks.MAGENTA_BANNER, Blocks.CYAN_BANNER, Blocks.ORANGE_BANNER, 
			Blocks.LIME_BANNER, Blocks.PURPLE_BANNER, Blocks.BROWN_BANNER, Blocks.PINK_BANNER);
	
	public static final WithStandardColors<Block> CANDLE_BLOCKS = WithStandardColors.of(
			Blocks.WHITE_CANDLE, Blocks.BLACK_CANDLE, Blocks.GRAY_CANDLE, Blocks.LIGHT_GRAY_CANDLE,
			Blocks.RED_CANDLE, Blocks.GREEN_CANDLE, Blocks.BLUE_CANDLE, Blocks.YELLOW_CANDLE,
			Blocks.LIGHT_BLUE_CANDLE, Blocks.MAGENTA_CANDLE, Blocks.CYAN_CANDLE, Blocks.ORANGE_CANDLE, 
			Blocks.LIME_CANDLE, Blocks.PURPLE_CANDLE, Blocks.BROWN_CANDLE, Blocks.PINK_CANDLE);
	
	public static final WithStandardColors<Block> TERRACOTTA_BLOCKS = WithStandardColors.of(
			Blocks.WHITE_TERRACOTTA, Blocks.BLACK_TERRACOTTA, Blocks.GRAY_TERRACOTTA, Blocks.LIGHT_GRAY_TERRACOTTA,
			Blocks.RED_TERRACOTTA, Blocks.GREEN_TERRACOTTA, Blocks.BLUE_TERRACOTTA, Blocks.YELLOW_TERRACOTTA, 
			Blocks.LIGHT_BLUE_TERRACOTTA, Blocks.MAGENTA_TERRACOTTA, Blocks.CYAN_TERRACOTTA, Blocks.ORANGE_TERRACOTTA,
			Blocks.LIME_TERRACOTTA, Blocks.PURPLE_TERRACOTTA, Blocks.BROWN_TERRACOTTA, Blocks.PINK_TERRACOTTA);

	public static final WithStandardColors<Block> GLAZED_TERRACOTTA_BLOCKS = WithStandardColors.of(
			Blocks.WHITE_GLAZED_TERRACOTTA, Blocks.BLACK_GLAZED_TERRACOTTA, Blocks.GRAY_GLAZED_TERRACOTTA, Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA,
			Blocks.RED_GLAZED_TERRACOTTA, Blocks.GREEN_GLAZED_TERRACOTTA, Blocks.BLUE_GLAZED_TERRACOTTA, Blocks.YELLOW_GLAZED_TERRACOTTA,
			Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA, Blocks.MAGENTA_GLAZED_TERRACOTTA, Blocks.CYAN_GLAZED_TERRACOTTA, Blocks.ORANGE_GLAZED_TERRACOTTA, 
			Blocks.LIME_GLAZED_TERRACOTTA, Blocks.PURPLE_GLAZED_TERRACOTTA, Blocks.BROWN_GLAZED_TERRACOTTA, Blocks.PINK_GLAZED_TERRACOTTA);

	public static final WithStandardColors<Block> STAINED_GLASS_BLOCKS = WithStandardColors.of(
			Blocks.WHITE_STAINED_GLASS, Blocks.BLACK_STAINED_GLASS, Blocks.GRAY_STAINED_GLASS, Blocks.LIGHT_GRAY_STAINED_GLASS,
			Blocks.RED_STAINED_GLASS, Blocks.GREEN_STAINED_GLASS, Blocks.BLUE_STAINED_GLASS, Blocks.YELLOW_STAINED_GLASS,
			Blocks.LIGHT_BLUE_STAINED_GLASS, Blocks.MAGENTA_STAINED_GLASS, Blocks.CYAN_STAINED_GLASS, Blocks.ORANGE_STAINED_GLASS, 
			Blocks.LIME_STAINED_GLASS, Blocks.PURPLE_STAINED_GLASS, Blocks.BROWN_STAINED_GLASS, Blocks.PINK_STAINED_GLASS);
	
	public static final WithStandardColors<Block> STAINED_GLASS_PANE_BLOCKS = WithStandardColors.of(
			Blocks.WHITE_STAINED_GLASS_PANE, Blocks.BLACK_STAINED_GLASS_PANE, Blocks.GRAY_STAINED_GLASS_PANE, Blocks.LIGHT_GRAY_STAINED_GLASS_PANE,
			Blocks.RED_STAINED_GLASS_PANE, Blocks.GREEN_STAINED_GLASS_PANE, Blocks.BLUE_STAINED_GLASS_PANE, Blocks.YELLOW_STAINED_GLASS_PANE,
			Blocks.LIGHT_BLUE_STAINED_GLASS_PANE, Blocks.MAGENTA_STAINED_GLASS_PANE, Blocks.CYAN_STAINED_GLASS_PANE, Blocks.ORANGE_STAINED_GLASS_PANE, 
			Blocks.LIME_STAINED_GLASS_PANE, Blocks.PURPLE_STAINED_GLASS_PANE, Blocks.BROWN_STAINED_GLASS_PANE, Blocks.PINK_STAINED_GLASS_PANE);
	
	public static final WithStandardColors<Block> SHULKER_BOX_BLOCKS = WithStandardColors.of(
			Blocks.WHITE_SHULKER_BOX, Blocks.BLACK_SHULKER_BOX, Blocks.GRAY_SHULKER_BOX, Blocks.LIGHT_GRAY_SHULKER_BOX,
			Blocks.RED_SHULKER_BOX, Blocks.GREEN_SHULKER_BOX, Blocks.BLUE_SHULKER_BOX, Blocks.YELLOW_SHULKER_BOX,
			Blocks.LIGHT_BLUE_SHULKER_BOX, Blocks.MAGENTA_SHULKER_BOX, Blocks.CYAN_SHULKER_BOX, Blocks.ORANGE_SHULKER_BOX, 
			Blocks.LIME_SHULKER_BOX, Blocks.PURPLE_SHULKER_BOX, Blocks.BROWN_SHULKER_BOX, Blocks.PINK_SHULKER_BOX);
	
	public static final WithStandardColors<Block> BED_BLOCKS = WithStandardColors.of(
			Blocks.WHITE_BED, Blocks.BLACK_BED, Blocks.GRAY_BED, Blocks.LIGHT_GRAY_BED,
			Blocks.RED_BED, Blocks.GREEN_BED, Blocks.BLUE_BED, Blocks.YELLOW_BED,
			Blocks.LIGHT_BLUE_BED, Blocks.MAGENTA_BED, Blocks.CYAN_BED, Blocks.ORANGE_BED, 
			Blocks.LIME_BED, Blocks.PURPLE_BED, Blocks.BROWN_BED, Blocks.PINK_BED);
}
